# Generated by Django 4.0.2 on 2022-04-05 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='address',
            fields=[
                ('addr_id', models.AutoField(primary_key=True, serialize=False)),
                ('house_no', models.CharField(max_length=20)),
                ('line_one', models.CharField(max_length=150)),
                ('line_two', models.CharField(max_length=150)),
                ('landmark', models.CharField(max_length=30)),
                ('is_corp', models.IntegerField()),
                ('delete_flag', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='area',
            fields=[
                ('area_id', models.AutoField(primary_key=True, serialize=False)),
                ('zipcode', models.CharField(max_length=6)),
                ('area_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='booking',
            fields=[
                ('bkg_id', models.AutoField(primary_key=True, serialize=False)),
                ('bkg_date', models.DateField()),
                ('bkg_time', models.TimeField()),
                ('bkg_status', models.IntegerField()),
                ('delete_flag', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='caste',
            fields=[
                ('caste_id', models.AutoField(primary_key=True, serialize=False)),
                ('caste_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
                ('feedback_date', models.DateField()),
                ('feedback_time', models.TimeField()),
                ('delete_flag', models.BooleanField(default=False)),
                ('bkg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bkg_feedback', to='admin_web.booking')),
            ],
        ),
        migrations.CreateModel(
            name='helper',
            fields=[
                ('h_id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=6)),
                ('dob', models.DateField()),
                ('photo', models.ImageField(blank=True, upload_to='helpers')),
                ('secondary_contact', models.CharField(max_length=10)),
                ('acc_no', models.IntegerField(null=True)),
                ('acc_holder_name', models.CharField(max_length=100, null=True)),
                ('branch_name', models.CharField(max_length=50, null=True)),
                ('ifsc_code', models.CharField(max_length=11, null=True)),
                ('aadharcard_no', models.IntegerField(null=True)),
                ('pancard_no', models.IntegerField(null=True)),
                ('aadharcard_img', models.ImageField(blank=True, null=True, upload_to='adhaarcard')),
                ('pancard_img', models.ImageField(blank=True, null=True, upload_to='pancard')),
                ('relative_id_proof', models.CharField(max_length=255, null=True)),
                ('temp_house_no', models.CharField(max_length=20)),
                ('temp_line_one', models.CharField(max_length=150)),
                ('temp_line_two', models.CharField(max_length=150)),
                ('temp_landmark', models.CharField(max_length=50)),
                ('perm_house_no', models.CharField(max_length=20)),
                ('perm_line_one', models.CharField(max_length=150)),
                ('perm_line_two', models.CharField(max_length=150)),
                ('perm_landmark', models.CharField(max_length=50)),
                ('delete_flag', models.BooleanField(default=False)),
                ('caste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caste_helper', to='admin_web.caste')),
                ('perm_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perm_area_helper', to='admin_web.area')),
            ],
        ),
        migrations.CreateModel(
            name='maidRequest',
            fields=[
                ('maid_request_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_of_request', models.DateField()),
                ('time_of_request', models.TimeField()),
                ('gender_pref', models.IntegerField()),
                ('age_pref', models.IntegerField()),
                ('req_status', models.IntegerField()),
                ('specification', models.CharField(max_length=150)),
                ('delete_flag', models.BooleanField(default=False)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_maidRequest', to='admin_web.address')),
            ],
        ),
        migrations.CreateModel(
            name='maidRequestDetails',
            fields=[
                ('req_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('count', models.IntegerField()),
                ('serv_start_date', models.DateField()),
                ('serv_end_date', models.DateField()),
                ('delete_flag', models.BooleanField(default=False)),
                ('maid_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maid_request_maidRequestDetails', to='admin_web.maidrequest')),
            ],
        ),
        migrations.CreateModel(
            name='religion',
            fields=[
                ('religion_id', models.AutoField(primary_key=True, serialize=False)),
                ('religion_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='services',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=10)),
                ('service_img', models.ImageField(blank=True, upload_to='serviceimg')),
                ('service_type', models.IntegerField()),
                ('criteria_of_charge', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=150)),
                ('delete_flag', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='state',
            fields=[
                ('state_id', models.AutoField(primary_key=True, serialize=False)),
                ('state_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('primary_contact', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=320, null=True)),
                ('pwd', models.CharField(max_length=64)),
                ('user_type', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='workingHours',
            fields=[
                ('working_hours_id', models.AutoField(primary_key=True, serialize=False)),
                ('time_slot', models.IntegerField(null=True)),
                ('start_hour', models.TimeField(blank=True, null=True)),
                ('end_hour', models.TimeField(blank=True, null=True)),
                ('delete_flag', models.BooleanField(default=False)),
                ('h', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='h_workingHours', to='admin_web.helper')),
            ],
        ),
        migrations.CreateModel(
            name='timeDetails',
            fields=[
                ('time_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_time', models.IntegerField()),
                ('request_type', models.CharField(max_length=6)),
                ('day_of_week', models.CharField(max_length=9)),
                ('time_slot_1', models.TimeField()),
                ('time_slot_2', models.TimeField()),
                ('time_slot_3', models.TimeField()),
                ('delete_flag', models.BooleanField(default=False)),
                ('req_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='req_details_timeDetails', to='admin_web.maidrequestdetails')),
            ],
        ),
        migrations.CreateModel(
            name='serviceProvided',
            fields=[
                ('serv_prov_id', models.AutoField(primary_key=True, serialize=False)),
                ('delete_flag', models.BooleanField(default=False)),
                ('h', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='h_serviceProvided', to='admin_web.helper')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_serviceProvided', to='admin_web.services')),
            ],
        ),
        migrations.CreateModel(
            name='ratings',
            fields=[
                ('rating_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('delete_flag', models.BooleanField(default=False)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_ratings', to='admin_web.feedback')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_ratings', to='admin_web.services')),
            ],
        ),
        migrations.CreateModel(
            name='payments',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_date', models.DateField()),
                ('payment_time', models.TimeField()),
                ('amount', models.IntegerField()),
                ('payment_status', models.IntegerField()),
                ('delete_flag', models.BooleanField(default=False)),
                ('bkg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bkg_payments', to='admin_web.booking')),
            ],
        ),
        migrations.AddField(
            model_name='maidrequestdetails',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_maidRequestDetails', to='admin_web.services'),
        ),
        migrations.CreateModel(
            name='holidayRequest',
            fields=[
                ('holiday_req_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_req', models.DateField()),
                ('time_req', models.TimeField()),
                ('date_holiday', models.DateField()),
                ('duration', models.IntegerField()),
                ('reason', models.CharField(max_length=150)),
                ('audio_req', models.CharField(max_length=255)),
                ('holiday_req_status', models.IntegerField()),
                ('delete_flag', models.BooleanField(default=False)),
                ('h', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='h_holidayRequest', to='admin_web.helper')),
            ],
        ),
        migrations.CreateModel(
            name='helperPaymentDetails',
            fields=[
                ('h_payment_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_date', models.DateField()),
                ('payment_amount', models.IntegerField()),
                ('payment_mode', models.CharField(max_length=50)),
                ('delete_flag', models.BooleanField(default=False)),
                ('h', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='h_helperPaymentDetails', to='admin_web.helper')),
            ],
        ),
        migrations.AddField(
            model_name='helper',
            name='special_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_service_helper', to='admin_web.services'),
        ),
        migrations.AddField(
            model_name='helper',
            name='temp_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp_area_helper', to='admin_web.area'),
        ),
        migrations.AddField(
            model_name='helper',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_helper', to='admin_web.user'),
        ),
        migrations.CreateModel(
            name='demo',
            fields=[
                ('demo_id', models.AutoField(primary_key=True, serialize=False)),
                ('demo_date', models.DateField()),
                ('demo_time', models.TimeField()),
                ('demo_status', models.IntegerField()),
                ('delete_flag', models.BooleanField(default=False)),
                ('h', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='h_demo', to='admin_web.helper')),
                ('req_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='req_details_demo', to='admin_web.maidrequestdetails')),
            ],
        ),
        migrations.CreateModel(
            name='complaint',
            fields=[
                ('complaint_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
                ('complaint_date', models.DateField()),
                ('complaint_time', models.TimeField()),
                ('complaint_reply', models.CharField(max_length=150)),
                ('complaint_status', models.IntegerField()),
                ('delete_flag', models.BooleanField(default=False)),
                ('bkg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bkg_complaint', to='admin_web.booking')),
            ],
        ),
        migrations.CreateModel(
            name='client',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('secondary_contact', models.CharField(max_length=10)),
                ('delete_flag', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_client', to='admin_web.user')),
            ],
        ),
        migrations.CreateModel(
            name='city',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=25)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_city', to='admin_web.state')),
            ],
        ),
        migrations.CreateModel(
            name='chargesArea',
            fields=[
                ('charge_area_id', models.AutoField(primary_key=True, serialize=False)),
                ('charges', models.IntegerField()),
                ('delete_flag', models.BooleanField(default=False)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area_chargesArea', to='admin_web.area')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_chargesArea', to='admin_web.services')),
            ],
        ),
        migrations.AddField(
            model_name='caste',
            name='religion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='religion_caste', to='admin_web.religion'),
        ),
        migrations.AddField(
            model_name='booking',
            name='h',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='h_booking', to='admin_web.helper'),
        ),
        migrations.AddField(
            model_name='booking',
            name='req_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='req_details_booking', to='admin_web.maidrequestdetails'),
        ),
        migrations.AddField(
            model_name='area',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_area', to='admin_web.city'),
        ),
        migrations.AddField(
            model_name='address',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area_address', to='admin_web.area'),
        ),
        migrations.AddField(
            model_name='address',
            name='c',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c_address', to='admin_web.client'),
        ),
    ]
