# Generated by Django 4.0.2 on 2022-04-05 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='secondary_contact',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
