# Generated by Django 4.0.2 on 2022-04-07 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_web', '0002_alter_client_secondary_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maidrequest',
            name='age_pref',
        ),
        migrations.RemoveField(
            model_name='maidrequest',
            name='specification',
        ),
        migrations.RemoveField(
            model_name='maidrequestdetails',
            name='count',
        ),
        migrations.RemoveField(
            model_name='maidrequestdetails',
            name='serv_end_date',
        ),
        migrations.AlterField(
            model_name='maidrequest',
            name='date_of_request',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='maidrequest',
            name='time_of_request',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
