# Generated by Django 4.0.2 on 2022-04-08 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_web', '0003_remove_maidrequest_age_pref_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='is_corp',
        ),
    ]
