from django import views
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('registerUserApi/', views.clientRegisterApi),
    path('getUserApi/', views.getClientData),
    path('getUserdata/<str:emailId>/', views.getClient),
    path('updateUserdata/<str:emailId>/', views.updateClient),
    path('index/', views.index, name='index'),
    path('', views.login, name='login'),
    #     path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('res_services/', views.res_services, name='res_services'),
    path('add_res_services/', views.add_res_services, name='add_res_services'),
    path('res_services/update/<str:key>', views.update_res_services,
         name='update_res_services'),
    path('res_services/delete/<str:key>', views.delete_res_services,
         name='delete_res_services'),
    path('comm_services/', views.comm_services, name='comm_services'),
    path('add_comm_services/', views.add_comm_services, name='add_comm_services'),
    path('comm_services/update/<str:key>', views.update_comm_services,
         name='update_comm_services'),
    path('comm_services/delete/<str:key>', views.delete_comm_services,
         name='delete_comm_services'),
    path('register_helper/', views.register_helper, name='register_helper'),
    path('work_details/', views.work_details, name='work_details'),
    path('manage_helper/', views.manage_helper, name='manage_helper'),
    path('manage_helper/<str:hid>',
         views.delete_helper, name='delete_helper'),
    path('edit_helper/<str:hid>', views.edit_helper, name='edit_helper'),
    path('edit_work_details/', views.edit_work_details, name='edit_work_details'),
    path('schedule/', views.schedule, name='schedule'),
    path('conf_details/', views.conf_details, name='conf_details'),
    path('edit_conf_details/', views.edit_conf_details, name='edit_conf_details'),
    path('salary_details/', views.salary_details, name='salary_details'),
    path('holiday_details/', views.holiday_details, name='holiday_details'),
    path('charges/', views.charges, name='charges'),
    path('charges/', views.new_charges, name='new_charges'),
    path('ratings/', views.ratings, name='ratings'),
    path('feedback/', views.feedback, name='feedback'),
    path('view_feedback/', views.view_feedback, name='view_feedback'),
    path('complaint/', views.complaint, name='complaint'),
    path('view_complaint/', views.view_complaint, name='view_complaint'),
    path('holiday_req/', views.holiday_req, name='holiday_req'),
    path('view_holiday_req/', views.view_holiday_req, name='view_holiday_req'),
    path('register_client/', views.register_client, name='register_client'),
    path('manage_client/', views.manage_client, name='manage_client'),
    path('manage_client/update/<str:userid>/<str:cid>', views.update_manage_client,
         name='update_manage_client'),
    path('manage_client/delete/<str:cid>', views.delete_manage_client,
         name='delete_manage_client'),
    path('add_maidreq/<str:cid>',
         views.add_maidreq, name='add_maidreq'),
    path('edit_maidreq/', views.edit_maidreq, name='edit_maidreq'),
    path('maid_req/', views.maid_req, name='maid_req'),
    path('demo_details/', views.demo_details, name='demo_details'),
    path('demofor_req/', views.demofor_req, name='demofor_req'),
    path('maidfor_demo/', views.maidfor_demo, name='maidfor_demo'),
    path('bookings/', views.bookings, name='bookings'),
    path('payments/', views.payments, name='payments'),
]
